### PR TITLE
Fix links to old repo

### PR DESCRIPTION
**Pull request by AgmasGold**
Just realised that the designer still has links to the old repository embedded within it. This PR fixes those issues, and also cleans up the About page a little bit, such as removing the "Modified" string from the page.

### CODE REVIEW

**Comment by AgmasGold** [comment]
Just had to fix some readme issues - accidentally commited the changed readme.md file that points people to this repository.

**Comment by FroggieFrog** [comment]
Something weird is going on with this PR. I can not check it out or merge it.
The source repo is also missing.

Do you want to commit a new PR or should I do it?

**Comment by AgmasGold** [comment]
I'll do it - that way you can do the review, and I won't end up weirdly reviewing my own code.

**Comment by AgmasGold** [comment]
Closing - moved to PR #174.

**Pull request closed without merging**
