### PR TITLE
#6 Implemented zooming around a point

### PR DESCRIPTION
**Pull request by Atria1234**
Placed objects are moved when zooming to keep same grid cell beneath the mouse cursor

Grid is still aligned to the top left, so mouse position in grid cell is changing, but will always stay on same grid cell

### CODE REVIEW

**Comment by AgmasGold** [comment]
Feels very nice to use - one thing I think this could benefit from is a setting to toggle it off. At the moment, you have no choice but to use zoom to point, and some people might be used to the current behaviour. I'd happy for it to be an opt-in to disable (e.g zoom to point mode is enabled by default).

**Comment by Atria1234** [comment]
I think zooming to the point is much more intuitive that it should be enabled forever. Is there even some window for these settings?

**Comment by AgmasGold** [comment]
So do I, but that might not be the opinion of everyone. Especially for this, where its very easy to just add a single branch in the code  to implement it. 

Not yet, just put in the "Tools" menu for now, and it can get moved to a settings page once there is one for it.

**Comment by Atria1234** [comment]
Waiting for the PreferencesWindow PR is merged so I can add new setting there

**Comment by FroggieFrog** [comment]
If you make it a new default, please make it obvious to the user that it can be changed back.
Maybe some kind of notification at the first start of the new version?

Also I noticed that the layout is "shaking" when zoomed in and out. Is there a way to smooth it out a little bit?

zoom_shaking

**Comment by AgmasGold** [comment]
I think that to smooth it out we'd need to offset the grid drawing by less than a full grid cell. `Point` is a pair of doubles, so could work.

> Maybe some kind of notification at the first start of the new version?

Maybe we should add a changelog notification on first startup - that would be a separate issue though.

**Comment by FroggieFrog** [comment]
Absolutely right about the changelog notification.
But I wanted to make sure that there is a special "warning" to the user that the behaviour of zooming has changed dramatically (and can be changed back).
If you decide to make it the new default.

**Comment by Atria1234** [comment]
It can be disables by default and no notification would be necessary. Inquisitive user can check the patch notes or preferences window.

I'll check how hard it will be to start drawing everything offset from top left corner.

**Comment by FroggieFrog** [comment]
Inside PR #238 I added the UI inside the preferences window.
The event inside the canvas looks like the following:
```csharp
protected override void OnMouseWheel(MouseWheelEventArgs e)
{
    if (!_appSettings.UseZoomToPoint)
    {
        GridSize += e.Delta / 100;
    }
    else
    {
        //will be added by PR #220
    }
}
```

**Comment by Atria1234** [comment]
Thank you, I'll look into this but now I don't have much spare time.

**Pull request merged**
