### PR TITLE
Use Windows clipboard instead of custom logic for clipboard

### PR DESCRIPTION
**Pull request by Atria1234**
Implemented pasting from Windows clipboard. Supported sources:
- .ad file
- .ad file's string content
- old copy/paste functionality

### CODE REVIEW

**Comment by FroggieFrog** [comment]
Good idea.
Because the logic is changed anyway, is it possible to move the clipboard logic from the `AnnoCanvas` to the corresponding `ViewModel`? Just to separate logic and UI a little bit more (compared to before).

**Comment by FroggieFrog** [comment]
@Atria1234 Because I modified the PR (extracted interfaces, added tests etc.) could you please check the PR again and give feedback if you are still happy with it?

**Comment by Atria1234** [comment]
Good idea to create interface for Clipboard to make it testable, looks good 👍

**Comment by FroggieFrog** [comment]
@Atria1234 Thank you for the valuable PR (as always)! 🎉

**Pull request merged**
