### PR TITLE
Implemented search for holes in the PolygonBoundaryFinderHelper

### PR DESCRIPTION
**Pull request by Atria1234**
obrazek

### CODE REVIEW

**Comment by FroggieFrog** [comment]
I think I'm missing something.
Is it a new feature or is it fixing a bug?
Is the provided image the before or after PR? (What is the opposite looking?)
What is the benefit of this PR? (To the user or the developer?)

**Comment by Atria1234** [comment]
I posted the "after" in the PR description, and here is the before: 
obrazek

In some cases it looks weird to look something like this:
obrazek
right side being completely filled in, while left side looks like there is a "hole" but it is just polygon which touches itself.

But this wasn't the main reason why I finished implementing this, but I can't remember now. I know I wanted to use this searcher for something else which required holes to be returned as well. It lowers the performance during the true influence polygon calculation, but it can be easily turned off in AnnoCanvas (basically by reverting the changes in that file + probably some minor refactoring).

I'll close this and if I remember why I needed this I'll reopen.

**Comment by StingMcRay** [comment]
I think it has to do with the Irrigation System you was making ... Not sure tho

**Comment by Atria1234** [comment]
Yeah, that's it. There could be a special overlay which iterates over all canals in the layout, generates bool[][] of irigated tiles and this algorithm could be used to show the area, correctly with holes.

I'll finish implementing this overlay and probably revert to just bounding polygon for the true influence range polygon calculation.

**Comment by Atria1234** [comment]
I guess that irrigation canals don't have special property, that would distinguish them from other placed objects, do they? Other than its name.

**Comment by StingMcRay** [comment]
No. it has not.

But does it need an extra marker, like road ?

**Comment by StingMcRay** [comment]
If you link it to the Identifier, else you have all languages to check :
`"Identifier": "WaterCanal"`
and let us know if it needs more then only that.

**Comment by Atria1234** [comment]
Yeah, I'll probably use the Identified, but this if Anno 1800 specific function, where do you think it should be?

**Comment by StingMcRay** [comment]
Around the code of your true influence range as that is also a Anno 1800 Specific function only

**Comment by FroggieFrog** [comment]
@Atria1234 @StingMcRay 
Is there still an issue with this PR and canals? Or is it ready to merge?

**Comment by Atria1234** [comment]
I currently don't have time to implement the canal coverage functionality. Theoretically this PR can be merged and the canal coverage being implemented in another PR.

**Pull request merged**
