### PR TITLE
Improve performance of rendering

### PR DESCRIPTION
**Pull request by FroggieFrog**
### What is missing? / What needs to be fixed?

- [x] selection of block tiles is rendered incorrect

---

This PR improves the performance of the `OnRender` method.
I hopefully tested all possible sitiuations, but please do also test it.

Looking at the diff it seems pretty big, but actually it is an optimization where everything is drawn to a backing `DrawingGroup` (acts as a kind of cached draw instructions) and those backing fields are (re)used when rendering the UI.

- grid lines are drawn once onto a backing `DrawingGroup` and only updated when necessary
- object selection is only drawn once onto a backing `DrawingGroup` and only updated when necessary
- objects are only drawn once onto a backing `DrawingGroup` and only updated when necessary
- influences are only drawn once onto a backing `DrawingGroup` and only updated when necessary
- optimized hot path to access "expensive" properties only when necessary (e.g. `_appSettings.ShowScrollbars`)
- optimized rendering of an empty canvas (methods return early if there are no objects)
- count of placed objects is only calculated when necessary

- [x] Depends on PR #363.

#### empty layout with mouse moving

combined_Profiler_empty_mouse-move

#### pretty big layout with selection with mouse moving

combined_Profiler_layout_with-selection

### CODE REVIEW

**Comment by FroggieFrog** [comment]
I fixed an issue with the selection while dragging an object. This was found by @StingMcRay [(via discord](https://discord.com/channels/571011757317947406/571064812042321927/914904394930204692))

#### Changes in behaviour to version 9.1

Also the mouse over highlight is not drawn anymore while dragging objects over other objetcs.
Also the selection highlight is removed on `MouseUp` after dragging a single object.

#### version 9.1

<details>
  <summary>Click to expand!</summary>  
 
drag_master
</details>

#### this PR

<details>
  <summary>Click to expand!</summary>
  
 drag_PR
</details>

**Review by StingMcRay — APPROVED** [review]
For so far i can see, its all oke now.
Thanks for the fixes @FroggieFrog

**Comment by Atria1234** [comment]
Instead of caching the QuadTree.Count the QuadTree should keep the count internally and update it with add/remove/clear methods. That way you don't have to remember that anytime you modify AnnoCanvas.PlacedObjects you also need to call AnnoCanvas.UpdatePlacedObjectCount

**Comment by FroggieFrog** [comment]
@Atria1234 Could you please add that optimization? I'm still pretty unfamiliar with the `QuadTree`.

**Comment by Atria1234** [comment]
Undo/Redo doesn't trigger stats to update

Place two objects, undo once:
obrazek

**Review by StingMcRay — APPROVED** [review]
Well done both :D

**Pull request merged**
