### PR TITLE
ColorPresetsDesigner: Remove already added identifier from list of available identifiers

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR removes already added identifiers from the list of available identifiers.

### CODE REVIEW

**Comment by FroggieFrog** [comment]
I need to recheck this and find out if there could be a legit case where this needs to be supported (same Identifier in 2 templates).

Maybe an asterisk in front of the Identifier in the combobox could be added in the mean time? Would this be sufficient (enough)?

**Comment by StingMcRay** [comment]
it is more that 2 same identifiers on the same TemplateName but other color, can be a problem too
like : Templatename 'a' color green : identifier 'bakery'
        Templatename 'a' color Blue : identifier 'bakery'
        
then the AD program will pick the first that is in the color.json file, that will be green if that is the first color written in the file
On some TemplateNames i use up to 3 or 4 colors to distinguish all Identifiers under that Templatename

**Comment by StingMcRay** [comment]
Ow wait, you mean names already used get a '*' in front of them
Yeah that can work too for me

**Comment by FroggieFrog** [comment]
I found no meanigful reason that an identifier could be present in more than one template.
So now all identifiers that are associated with a template are removed from the combobox.

**Comment by StingMcRay** [comment]
Gone test this soon, prob 13:30 at my time (that is in 2 hours)

**Review by StingMcRay — APPROVED** [review]
This is work like a charm : Thanks for the fast solution 👍

**Pull request merged**
