### PR TITLE
ColorPresetsDesigner: Some QOL improvements

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR improves the `ColorPresetsDesigner`:

- identifiers for template are sorted
- added color is selected
- after deleting the first color is selected
- adjust designer view
- scrollbars actually work

### CODE REVIEW

**Comment by StingMcRay** [comment]
The following is working 
- [x] identifiers for template are sorted
- [x] added color is selected
- [x] after deleting the first color is selected
- [ ] adjust designer view _(i do not know what i need to see here)_
- [x] scrollbars actually work

If it is possible, can you sort the list when i add a new color to the template list

_Added a color, that starts with a F and is on top of the list as that is "default" by the program
When i add a other new color, i like to have the F one i added before be sorted in the list where it belongs, while the new added color is on top of the list.
my idea is : when push the + on the template list sort first then add the new template one_

**Comment by FroggieFrog** [comment]
The list uses the auto sort of CollectionView, so it should already be sorted.
But I will check what the issue is and see if I can fix it.

**Review by StingMcRay — CHANGES_REQUESTED** [review]
I noticed one thing : 
I have 2 Bakeries in the list :
Bakery (anno 1404)
bakery (anno 2070)

afbeelding

The last one still appear in the list as it has no capital (problem lies in the build of  the assets from 2070 where all thinks added with small letters)
As the anno designer has no problems with it and select the color form the first bakery, i request, if possible, to filer this too.

The PresetParser however does not capitalize the first chars of the assets from 1404 and 2070 as it is compact. if you like / want i can fix it there too

**Comment by FroggieFrog** [comment]
The combobox is filled with all identifiers that were found in the building presets file.
So the different capitalization has to be in the presets file.

**Do I get your request correct that you only want a single entry (e.g. for `Bakery` and `bakery`) and all entries should start with an uppercase letter?**

Are you sure that the app is fine with that?
I'm fine with it if the app is fine with it 😃

**Comment by StingMcRay** [comment]
> Do I get your request correct that you only want a single entry (e.g. for Bakery and bakery) and all entries should start with an uppercase letter?

No, i mean can  you check all identifiers in lowercase (string.ToLower()) so that anno 2070 identifiers (that is in lowercase's all the time) that are the same are anno 1404 identifiers (that starts with a capital letter) are disappear from the combo-box as well? 
(this was option 1)

If this is not possible i am willing to let all identifiers on Anno 2070 starting with a capital letter (as that is not the case in the preset-parser at the moment an read plain in what is in the assets, this we never changed from when we got the project)

**Comment by FroggieFrog** [comment]
As far as I can see everytime the `Identifier` is checked/compared `StringComparison.OrdinalIgnoreCase` is used.
Therefor I will convert all identifiers found in the building presets to a first uppercase letter and remove duplicates.

**Review by StingMcRay — APPROVED** [review]
Thanks again on your good work
All things work as it should be now 👍

**Pull request merged**
