### PR TITLE
Add blocking tiles (fix #374)

### LINKED ISSUE #374: Add a "blocking building"
Because it was requested on discord a couple of times, it would be benficial to add a `blocking building` to the presets.
This could be used for outlines of island or just marking a blocked area.

Properties of the `blocker building`:
- has a size of 1x1
- is **not** respected in the statstistics
- is **not** respected when calculating the layout size
- is **not** respected when calculating the influence
- does **not** have a label
- should **not** have a border

Open questions:
- Which predefined color does it have?
- What is the name of the `Template`? (e.g. `Blocker`)
- Should it be visible/respected in the `Selected buildings` area?
- Is it beneficial to add more sizes? (similiar to the different road presets)
- Implement it as `ExtraPreset` inside of `PresetParser`? (similiar to the different road presets)

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR adds support for blocking tiles which will fix #374.

- [x] add blocking tiles to `PresetParser`
- [x] add localization to `BlockingTile`
- [x] ignore `Template` _Blocker_ in all calculations
- [x] generic way to ignore specific `Template`s in calculations
- [x] add tests to `PresetParser`
- [x] add tests for calculations
- [x] ignore `BlockingTile` on selection
- [x] fix `InfluenceRadius` on `ExtraPresets` (use `double` instead of `int`)
- [x] tests for central location that handles ignored objects
- [x] basic perf tests to make sure it is still useable

### CODE REVIEW

**Review by StingMcRay — APPROVED** [review]
PresetParser Part is Oke
Edited the `BlockingTile.cs` see commit details why
Only problem is the removing of the "Block Tile" but see https://discord.com/channels/571011757317947406/571064812042321927/915251843129557013 for explanation

**Comment by FroggieFrog** [comment]
@StingMcRay Actually the `Faction` of `BlockingTile` has to be set.
The current logic of the `PresetsTreeViewModel` ignores all entries where `Faction is null`: [see here](https://github.com/AnnoDesigner/anno-designer/blob/1c38e42a1edd15ccd8a9ae7f62546cde89fe723e/AnnoDesigner/ViewModels/PresetsTreeViewModel.cs#L220)

So I added back a value for `Faction`. But instead of `Blocker` I chose `Common` because that way it is easier to add more `BlockingTile`s in future updates.
And it looks/feels better than this:
grafik

**Comment by StingMcRay** [comment]
Let me check some things ....

**Comment by StingMcRay** [comment]
You're right, my bad, groups is what can be null or not ....

**Comment by FroggieFrog** [comment]
Currently the performance of `StatisticsCalculationHelper.CalculateStatistics` is getting worse, but we are still talking about microseconds.
Maybe some optimization of `IEnumerableExtensions.WithoutIgnoredObjects` is possible and could be made via another PR.

#### Benchmark results

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1387 (21H1/May2021Update)
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4420.0), X64 RyuJIT
  Job-WRGTJA : .NET Framework 4.8 (4.8.4420.0), X64 RyuJIT

Runtime=.NET Framework 4.8  Force=True  

```
|        Method | Runs |         Mean |      Error |     StdDev | Ratio | RatioSD |   Gen 0 | Allocated |
|-------------- |----- |-------------:|-----------:|-----------:|------:|--------:|--------:|----------:|
| **CurrentMaster** |    **1** |     **10.79 μs** |   **0.131 μs** |   **0.109 μs** |  **1.00** |    **0.00** |  **0.0153** |     **129 B** |
|            PR |    1 |     28.20 μs |   0.328 μs |   0.307 μs |  2.62 |    0.04 |  0.0305 |     233 B |
|               |      |              |            |            |       |         |         |           |
| **CurrentMaster** |  **100** |  **1,078.37 μs** |   **9.640 μs** |   **7.526 μs** |  **1.00** |    **0.00** |  **1.9531** |  **12,848 B** |
|            PR |  100 |  2,841.65 μs |  48.871 μs |  43.323 μs |  2.63 |    0.05 |       - |  23,294 B |
|               |      |              |            |            |       |         |         |           |
| **CurrentMaster** | **1000** | **10,869.74 μs** |  **57.512 μs** |  **44.902 μs** |  **1.00** |    **0.00** | **15.6250** | **128,386 B** |
|            PR | 1000 | 28,553.49 μs | 562.090 μs | 577.225 μs |  2.64 |    0.05 | 31.2500 | 232,708 B |

<details>
  <summary>benchmark code</summary>
  
  ```csharp
        [Params(1, 100, 1000)]
        public int Runs { get; set; }

        [Benchmark(Baseline = true)]
        public void CurrentMaster()
        {
            for (int i = 0; i < Runs; i++)
            {
                _ = _helper_master.CalculateStatistics(_list);
            }
        }

        [Benchmark]
        public void PR()
        {
            for (int i = 0; i < Runs; i++)
            {
                _ = _helper_PR.CalculateStatistics(_list);
            }
        }
  ```
</details>

**Review by StingMcRay — APPROVED** [review]

**Comment by FroggieFrog** [comment]
A run with a profiler also confirms that it is slower, but still we are talking about time spans that are ignoreable.

grafik

**Pull request merged**
