### PR TITLE
Hide app.config in explorer (fix #160)

### LINKED ISSUE #160: AnnoDesigner.exe vs AnnoDesigner.exe.config
On windows explorer, with the option **'hide known extensions'** enabled, then some users will see in explorer the following:
```
AnnoDesigner
AnnoDesigner.exe
```
Unknown users who not know how Explorer works try to start the 'AnnoDesigner.exe' while this is the config file for Anno Designer.

So, when you get an error like this : 
afbeelding
Run the 'AnnoDesigner' (the one without extension showed, but with the programs icon) that will solve this Error.
afbeelding

Question to the Devs, 
Is it possible to remove the '.exe' from the 'AnnoDesigner.exe.config

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR sets the `Hidden` attribute to the `app.config` file and uses 7zip to create the zip file for release.
The build in (in cake) zip functionality does not respect the file attributes, but 7zip does.
The created zip file can still be extracted with the explorer.
This should fix #160.

### CODE REVIEW

**Comment by StingMcRay** [comment]
Is it mend to be that the "Read only" Attribute is removed from the file?

The Hidden File Attribute is working as intended

**Comment by StingMcRay** [comment]
Never mind the Read Only Attribute... i had an other file selected seams...

**Review by StingMcRay — APPROVED** [review]
Works as intended : Hidden File Attribute was nice set to the file "AnnoDesigner.exe.config"

**Comment by FroggieFrog** [comment]
There should never be a read only flag at the app.config. At least the log level could be configured with it.

**Comment by StingMcRay** [comment]
> There should never be a read only flag at the app.config. At least the log level could be configured with it.

I know, thats why i said never mind... seams i had an other file selected back when i check the older version :D

**Pull request merged**
