### PR TITLE
Fix #133: check for duplicate identifiers in PresetParser

### LINKED ISSUE #133: check identifier for uniqueness
Add a check against all presets to make sure the identifier is unique.

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR fixes #133 by adding a `Validator` to the `PresetParser`.

This `Validator` checks all given buildings for uniquness of their `Identifier` property.
If there are duplicates found, all duplicate `Identifier` values will be printed to the console.

### CODE REVIEW

**Review by StingMcRay — COMMENTED** [review]
Would you please be so kind to check my changes too on the files
ValidatorTests where oke

**Review by StingMcRay — APPROVED** [review]
Everything looks OK for

**Comment by FroggieFrog** [comment]
@StingMcRay
I made some changes and also add an option (`-validate`) to validate an existing file (see image).
Could please check again if this ok for you?

PresetParser

**Comment by StingMcRay** [comment]
Ow thanks that is nice done :)
i will check tomorrow if you don't mind, i got something else on my hand so...

**Review by StingMcRay — APPROVED** [review]
Works perfect,
However on en unknow path / file the applications will exit directly, no msg no retry

**Pull request merged**
